Increment 13
Galish/url-shortener pull request #14
Opened 2023-11-08 15:43 UTC by Galish

2023-11-13 13:24 UTC, capsulated requested changes
Написал всё в комментариях.

И насчёт context - он, конечно, передаётся почти во всех параметра, но не используется в полной мере. Это пока не критично, так как в следующих спринтах к этому придём.

2023-11-13 13:24 UTC, capsulated commented on cmd/shortener/main.go
> +func newRepo(cfg *config.Config) (repository.Repository, error) {
❌ В `Repository` необходимо перенести

2023-11-13 13:24 UTC, capsulated commented on internal/app/compress/writer.go
> +	if cw.isContentTypeSupported() {
Тут упустил момент в прошлом ревью: если у нас есть связь компрессора с элементами http запросов (status code, content type и тп) - то лучше их переместить в пакет хендлеров.

2023-11-13 13:24 UTC, capsulated commented on internal/app/handlers/api_shorten.go
> +		w.WriteHeader(http.StatusConflict)
⚠️ Здесь `return` бы по-хорошему, без else. Плохо читается: не сразу видно что в итоге выполнится в каком случае, так как дальше  http.StatusInternalServerError ещё может вернуться. Вообще http.StatusCreated в самом конце хендлера  хорошо бы выставить. А до него в случае негативных кейсов - статус и return в каждом из  них

2023-11-13 13:24 UTC, capsulated commented on internal/app/handlers/shorten.go
> +	w.Write([]byte(fullLink))
⚠️ В случае http.StatusConflict fullLink всё равно звпишестя в body?

2023-11-13 13:24 UTC, capsulated commented on internal/app/repository/db/db.go
> +	for _, entry := range entries {
⚠️ Выполниться много insert'ов? Лучше одним запросом как-то реализовать. Один из вариантов это [copy](https://pkg.go.dev/github.com/jackc/pgx#hdr-Copy_Protocol)

2023-11-15 16:26 UTC, Galish commented on cmd/shortener/main.go
> +func newRepo(cfg *config.Config) (repository.Repository, error) {
Готово. Для того, чтобы избежать циклических зависимосей, пришлось перенести все, что связано с ошибками в отдельный подпакет `repository/errors`.

2023-11-15 16:28 UTC, Galish commented on internal/app/compress/writer.go
> +	if cw.isContentTypeSupported() {
Перенес в пакет `middleware`, к утилитам, которые работают непосредственно запросами.

2023-11-15 16:29 UTC, Galish commented on internal/app/repository/db/db.go
> +	for _, entry := range entries {
Реализовал с помощью `pgx conn.CopyFrom`.

2023-11-15 16:41 UTC, Galish commented on internal/app/handlers/shorten.go
> +	w.Write([]byte(fullLink))
Да, и в соответсвии с заданием, уникальный идентификатор будет заменен идентификатором уже существующей записи.

2023-11-15 16:51 UTC, Galish commented on internal/app/handlers/api_shorten.go
> +		w.WriteHeader(http.StatusConflict)
Каждый из предложенных вариантов реализации приводит к падению юнит тестов. В хендлере необходимо соблюсти следующий порядок:
1. w.Header().Set("Content-Type", "application/json")
2. w.WriteHeader(...)
3. json.NewEncoder(w).Encode(resp)
Что делает невозможным внесение вышеописанных изменений.

2023-11-15 19:20 UTC, capsulated commented on internal/app/handlers/api_shorten.go
> +		w.WriteHeader(http.StatusConflict)
Хммм 🤔

2023-11-15 19:21 UTC, capsulated approved these changes
👍

2023-11-16 06:39 UTC, merged