Increment 15
Galish/url-shortener pull request #16
Opened 2023-11-26 08:24 UTC by Galish

2023-11-28 13:47 UTC, capsulated requested changes
В принципе, всё классно, никаких критичных замечаний нет.

Так как время ещё немного есть, то отметил пару важных замечаний, если есть время и желание - можно оптимизировать. Если нет - то просто на комент ответь кратко, что думаешь по этому поводу, и присылай обратно - я в любом случае приму работу

2023-11-28 13:47 UTC, capsulated commented on internal/app/handlers/router.go
> +		middleware.Apply(
Не очень хорошо, что к каждому роуту мидлваря добавляется отдельно. Хорошо бы подключить  ко со всем роутам те миддлвари, которые во всех роутах участвуют. Хотя это только logger 🤔  Тогда, скорее для справки оставлю комментарий, так как мидлвари тем и удобны, что можно сразу на все хендлеры добавить или на часть хендлеров определённого пути

⚠️ Можно их на `r.Group(func(r chi.Router) { ... }` всё же, и к группе свой набор middlware подключить

2023-11-28 13:47 UTC, capsulated commented on internal/app/middleware/apply.go
> +func Apply(
Какая-то подозрительная конструкция...  🤔 не пойму только, в чём))

Скорее всего, что всё же за счёт `router.Group` это реализуется, с помощью `router.Use(...)`, так проще и нет дублирования (DRY)

2023-11-28 13:47 UTC, capsulated commented on internal/app/repository/db/delete.go
> +		for _, link := range shortLinks {
⚠️ Не очень хорошо, что в цикле множество sql запросов, в идеале один запрос сделать. Будет не очень красиво в коде, скорее всего, зато хорошо в плане отпимизации нагрузки на БД. Там несколько подходов есть

2023-11-29 08:02 UTC, Galish commented on internal/app/middleware/apply.go
> +func Apply(
Эта утилита наподобие `compose` из JavaScript.
Реализовал применение мидлварей в соответствии с твоими рекомендациями. Спасибо!

2023-11-29 08:03 UTC, Galish commented on internal/app/handlers/router.go
> +		middleware.Apply(
Переделал. Спасибо за совет!

2023-11-29 17:25 UTC, Galish commented on internal/app/repository/db/delete.go
> +		for _, link := range shortLinks {
Реализовал единым запросом с использованием [squirrel](https://github.com/Masterminds/squirrel).

2023-11-30 20:46 UTC, capsulated approved these changes
Всё отлично! 🚀

2023-11-30 20:46 UTC, capsulated commented on internal/app/handlers/router.go
> +	router.Group(func(r chi.Router) {
🔥

2023-12-01 06:13 UTC, merged