Increment 18
Galish/url-shortener pull request #19
Opened 2024-01-29 05:13 UTC by Galish

2024-02-01 17:31 UTC, capsulated requested changes
Для документации необходимо вынести в `pkg` хоть какой-то функционал.  Можно компрессор и аунтификатор. Подробнее написал в комментарии

И если получится, то профили всего приложения вывести в два файла, или хотя бы bash скрипт, который будет агрегировать значения и выводить общее (было - стало). Но это не супер критично, по желанию

2024-02-01 17:31 UTC, capsulated commented on internal/app/compress/compressor.go
Этот пакет перенести из `internal` в `pkg`, чтобы в документации хоть что-то отображалось. Также, можно пакет авторизации и даже storage вынести в pkg. Всё подряд в `internal` не совсем правильная практика. Это тоже, что и private переменные в пакете, но только для пакета, считай, все папки internal - это приватные пакеты

2024-02-02 06:53 UTC, Galish commented on internal/app/compress/compressor.go
1. Сгенерировал 2 профиля для пакета `/handlers`.
2. Перенес 3 пакета из `/internal` в `/pkg`. Repository не стал трогать, т.к. он реализует логику приложения и не подходит для переиспользования. Документация и примеры для пакетов внутри `/internal` доступны с параметром `/?m=all`.

2024-02-02 22:28 UTC, capsulated approved these changes
Компрессор и автогризация - супер.

По хендлерам - если internal, то это не экспортируемые и не документируемые пакеты. 

Можно такой подход применить: берём выпускной gofermart, сравниваем в url-shortener. И тот функционал, который дублируется - это пакеты для `pkg`, которые можно переиспользовать. Для хендлеров - это swagger. 

Я на вебинаре немного затрону эту тему, так как наш коллега-студент всех вводит в заблуждение со своим m=all.

В любом случае, всё круто, молодец, апрувлю.

2024-02-06 05:59 UTC, merged