Increment 23
Galish/url-shortener pull request #24
Opened 2024-02-24 14:58 UTC by Galish

2024-02-27 17:14 UTC, capsulated requested changes
Совсем небольшие исправления надо бы сделать, написал в коментах

2024-02-27 17:14 UTC, capsulated commented on cmd/shortener/main.go
> +	shutdowner := shutdowner.New(server, handler, store)
Имя пакета совпадает с именем переменной, лучше такого не допускать

2024-02-27 17:14 UTC, capsulated commented on internal/app/config/file.go
> +	return nil
Если в месте вызова функции не проверяется на наличие ошибки, то может и не возвращать её? Или добавить обработку и лог в месте вызова

2024-02-27 17:14 UTC, capsulated commented on internal/app/config/config.go
> +	parseFile(configFile, file)
Тут `err` возвращается, но не проверяется, может он и не нужен?

2024-02-27 17:14 UTC, capsulated commented on pkg/shutdowner/shutdowner.go
> +func New(list ...io.Closer) *shutdowner {
Оу, целый пакет 🤔 Обычно, прямо cmd логику `gracefully shutdown` добавляют, но в нашем случае можно создать пакет `app`, и в нём создать сервер и в конце запуска (`app.Run()` к примеру) добавить прослушивание сигналов - обычно так делают. 

Это больше для информации, создание специального пакета тоже вариант

2024-02-27 17:14 UTC, capsulated commented on pkg/shutdowner/shutdowner.go
> +		c.Close()
Хмм, ты слайс сервисов решил сделать? Интересно 🤔 почему бы и нет )) Но ошибку, которая возвращает `Close()` по-хорошему, надо бы вывести на экран, вдруг что-то подвисло и не закрылось корректно

2024-02-27 17:14 UTC, capsulated commented on pkg/shutdowner/shutdowner.go
> +func (sd shutdowner) Shutdown() {
Методы выше с ресивером по указателю, а текущий и нижестоящий - без указателя. IDE и компилятор не ругается?
```
Struct shutdowner has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation. 
```

2024-02-27 17:14 UTC, capsulated commented on pkg/shutdowner/shutdowner.go
> +func New(list ...io.Closer) *shutdowner {
И идее, если есть глобальный конструктор, то и сам тип должен быть глобальным:
```
Exported function with the unexported return type 
```

2024-02-28 16:32 UTC, Galish commented on cmd/shortener/main.go
> +	shutdowner := shutdowner.New(server, handler, store)
Исправил

2024-02-28 16:33 UTC, Galish commented on internal/app/config/file.go
> +	return nil
Реализовал логирование ошибки вместо ее возврата

2024-02-28 16:33 UTC, Galish commented on internal/app/config/config.go
> +	parseFile(configFile, file)
Исправил

2024-02-28 16:39 UTC, Galish commented on pkg/shutdowner/shutdowner.go
> +func New(list ...io.Closer) *shutdowner {
По мне так неплохая абстракция реализующая логику `gracefully shutdown` без необходимости городить ее в пакете `main`.  😃

2024-02-28 16:41 UTC, Galish commented on pkg/shutdowner/shutdowner.go
> +		c.Close()
Ты мне подкинул идею аппендить в слайс функции `Close` вместо самих сервисов. Имеет ли такая реализация право на жизнь?

2024-02-28 16:42 UTC, Galish commented on pkg/shutdowner/shutdowner.go
> +		c.Close()
Добавил логирование ошибок закрытия сервиса

2024-02-28 16:43 UTC, Galish commented on pkg/shutdowner/shutdowner.go
> +func (sd shutdowner) Shutdown() {
Ни IDE, ни компилятор не ругнулись. Не думал что это критичный момент.
Исправил согласно рекомендации.

2024-02-28 16:43 UTC, Galish commented on pkg/shutdowner/shutdowner.go
> +func New(list ...io.Closer) *shutdowner {
Исправил

2024-02-28 17:37 UTC, capsulated commented on pkg/shutdowner/shutdowner.go
> +		c.Close()
> Ты мне подкинул идею аппендить в слайс функции `Close` вместо самих сервисов. Имеет ли такая реализация право на жизнь?

Да-да, вполне. Но, конечно, менее наглядно становится

2024-02-28 17:38 UTC, capsulated commented on pkg/shutdowner/shutdowner.go
> +func (sd shutdowner) Shutdown() {
Компилятор ок прочитает. Не критично, но в каких-то ситуациях может создать небольшие проблемы

2024-02-28 17:39 UTC, capsulated approved these changes
Супер  👍👍

2024-03-04 13:26 UTC, merged